In [1]:
import numpy as np

### Rules: 
Below image is the maze. Rooms 0~4 are accessible through doors. 

5 is the exit, and room 4 has direct access to exit.

How to find the path to exit from any room?

![maze](https://github.com/YangHong92/ReinforcementLearning/raw/master/maze_Qlearning/maze.png)

# Simulate Maze Problem

Update Q table:

$Q(S_t, A_t) \leftarrow Q(S_t, A_t) + \alpha[R_{t+1} + \gamma max Q(S_{t+1}, A_t) - Q(S_t, A_t)] $

simply set $\alpha=1$, we have:

$Q(S_t, A_t) \leftarrow R_{t+1} + \gamma max Q(S_{t+1}, A_t) $

In [36]:
# discount value
GAMMA = 0.8

# Q table
Q = np.zeros((6,6))

# Reward matrix (initailizing according to accessibility between rooms)
# state (current_room) * action (next_room)
# -1: not accessible, 0: accessible to other room, 100: accessible to exit)
R = np.asarray([\
    [-1,-1,-1,-1,0,-1],
   [-1,-1,-1,0,-1,100],
   [-1,-1,-1,0,-1,-1],
   [-1,0, 0, -1,0,-1],
   [0,-1,-1,0,-1,100],
   [-1,0,-1,-1,0,100]])

# 过选取最大动作值来进行最优策略学习
def getMaxQ(state):
    # print("curAction: ", state, "max value: ", max(Q[state, :]))
    return max(Q[state, :]) # get max value of each row通

# QLearning
def QLearning(state):
    curAction = None
    # action (next room): 0-5
    for action in range(6):
        if(R[state][action] == -1):
            Q[state, action] = 0
        else:
            curAction = action
            # update current [state, action] with the max value of next action
            Q[state, action] = R[state][action] + GAMMA * getMaxQ(curAction) # getMaxQ(curAction) return value from next action

In [37]:
for count in range(60):
    print("====iteration:", count,"====")
    # state (room): 0-5
    for i in range(6):
        QLearning(i)
    print(Q)

# keep one decimal
np.set_printoptions(precision=1)
print()

# 走了5次
print(Q/5)

====iteration: 0 ====
[[  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0. 100.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.  80.   0.   0.   0.   0.]
 [  0.   0.   0.  64.   0. 100.]
 [  0.  80.   0.   0.  80. 164.]]
====iteration: 1 ====
[[  0.    0.    0.    0.   80.    0. ]
 [  0.    0.    0.   64.    0.  231.2]
 [  0.    0.    0.   64.    0.    0. ]
 [  0.  185.   51.2   0.   80.    0. ]
 [ 64.    0.    0.  148.    0.  231.2]
 [  0.  185.    0.    0.  185.  248. ]]
====iteration: 2 ====
[[  0.    0.    0.    0.  185.    0. ]
 [  0.    0.    0.  148.    0.  298.4]
 [  0.    0.    0.  148.    0.    0. ]
 [  0.  238.7 118.4   0.  185.    0. ]
 [148.    0.    0.  191.    0.  298.4]
 [  0.  238.7   0.    0.  238.7 298.4]]
====iteration: 3 ====
[[  0.    0.    0.    0.  238.7   0. ]
 [  0.    0.    0.  191.    0.  338.7]
 [  0.    0.    0.  191.    0.    0. ]
 [  0.  271.  152.8   0.  238.7   0. ]
 [191.    0.    0.  216.8   0.  338.7]
 [  0.  271.    0.    0.  271.  338.7]]
====iter

![maze_path](https://github.com/YangHong92/ReinforcementLearning/raw/master/maze_Qlearning/maze_path.png)